{
  "video": {
    "sites": [
    
    {"key": "豆瓣",
      "name": "念心丨豆瓣丨部分接口于互联网整理",
    "type": 3,
    "indexs": 1,
  "api": "./douban_open.js"},

    {"key": "南瓜",
      "name": "念心丨南瓜",
    "type": 3,
  "api": "./ng_open.js"},

    {"key": "爱看机器人",
      "name": "念心丨爱看",
    "type": 3,
  "api": "./ikanbot_open.js"},

    {"key": "素白白",
      "name": "念心丨素白",
    "type": 3,
  "api": "./subaibai_open.js"},

   {"key": "一起看",
    "name": "念心丨一起",
   "type": 3,
 "api": "./yqktv_open.js"},

   {"key": "耐看点播",
    "name": "念心丨耐看",
   "type": 3,
 "api": "./nkvod_open.js"},

   {"key": "低端影视",
    "name": "念心丨低端",
   "type": 3,
 "api": "./ddys_open.js"},

    {"key": "天天",
      "name": "念心丨天天",
    "type": 3,
  "api": "./tiantian_open.js"},

   
   {"key": "玩偶哥哥",
    "name": "念心丨玩偶",
   "type": 3,
   "api": "./wogg_open.js",
 "ext": "填入你的阿里token"},

    {"key": "玩偶表哥",
      "name": "念心丨表哥",
    "type": 3,
    "api": "./wobg_open.js",
  "ext": "填入你的阿里token"},

     
    {"key": "玄天影视",
      "name": "念心丨玄天",
    "type": 3,
  "api": "./yjys_open.js"},

   {"key": "非凡资源",
    "name": "念心丨非凡",
   "type": 3,
 "api": "./ff_open.js"},

   {"key": "voflix",
    "name": "念心丨Vofx",
   "type": 3,
 "api": "./voflix_open.js"},

   {"key": "映迷",
    "name": "念心丨映迷",
   "type": 3,
 "api": "./ym_open.js"},

   {"key": "麻衣呀",
    "name": "念心丨麻衣",
   "type": 3,
 "api": "./mayiya_open.js"},
      
      {
        "key": "dsxys",
        "name": "念心丨师兄",
        "type": 3,
        "api": "./dsxys_open.js"
      },

   {"key": "电影先生",
    "name": "念心丨先生",
   "type": 3,
 "api": "./dyxs_open.js"},

  {"key": "4K影视",
    "name": "念心丨四克",
  "type": 3,
"api": "./4kys_open.js"},

   {"key": "91free",
    "name": "念心丨九一",
   "type": 3,
 "api": "./91free_open.js"},

   {"key": "金曼TV",
    "name": "念心丨金曼",
   "type": 3,
 "api": "./jinm_open.js"},

   {"key": "起飞影院",
    "name": "念心丨起飞",
   "type": 3,
 "api": "./qfys_open.js"},

   
    {"key": "cntv-news",
      "name": "聚视丨新闻",
    "type": 3,
  "api": "./cntv_news.js"},

    {"key": "cntv",
      "name": "聚视丨综合",
    "type": 3,
  "api": "./cntv_open.js"},

    {"key": "live0",
      "name": "采集丨爱听",
    "type": 3,
    "api": "./caiji.js",
  "ext": "https://catbox.n13.club/yy.php"},

    {"key": "live1",
      "name": "采集丨音乐",
    "type": 3,
    "api": "./caiji.js",
  "ext": "https://catbox.n13.club/?ext=1"},

    {"key": "live2",
      "name": "采集丨教育",
    "type": 3,
    "api": "./caiji.js",
  "ext": "https://catbox.n13.club/?ext=2"},

    {"key": "live3",
      "name": "采集丨美女",
    "type": 3,
    "api": "./caiji.js",
  "ext": "https://catbox.n13.club/?ext=3"},

    {"key": "live9",
      "name": "采集丨电视",
    "type": 3,
    "api": "./caiji.js",
  "ext": "https://tvbox.serv00.net/live.php"},

    {"key": "live4",
      "name": "采集丨吉祥",
    "type": 3,
    "api": "./caiji.js",
  "ext": "https://catbox.n13.club/?ext=4"},

    {"key": "live5",
      "name": "采集丨俊俊",
    "type": 3,
    "api": "./caiji.js",
  "ext": "https://catbox.n13.club/?ext=http://home.jundie.top:81/Cat/tv/live.txt"},

        
    {"key": "360ba",
      "name": "念心丨看球",
    "type": 3,
    "api": "./360ba_open.js",
    "searchable": 0,
    "changeable": 0,
    "style": {"type": "list"}},

    {"key": "武享UFC",
      "name": "念心丨UFC",
    "type": 3,
  "api": "./ufc_open.js"},

    
    {"key": "58动漫",
      "name": "念心丨58",
    "type": 3,
  "api": "./58dm_open.js"},

   {"key": "anfun",
    "name": "念心丨爱番",
   "type": 3,
 "api": "./anfun_open.js"},

   {"key": "爱动漫",
    "name": "念心丨爱漫",
   "type": 3,
 "api": "./adm_open.js"},

      {
        "key": "anfun",
        "name": "念心丨Afun",
        "type": 3,
        "api": "./anfun_open.js"
      },

   {"key": "兔小贝",
    "name": "念心丨小贝",
   "type": 3,
 "api": "./tuxiaobei_open.js"},

    {"key": "贝乐虎",
      "name": "念心丨乐虎",
    "type": 3,
  "api": "./ubestkid_open.js"},

    {"key": "播视网",
      "name": "念心丨童趣",
    "type": 3,
  "api": "./boosj_open.js"},

    
    {"key": "酷奇MV",
      "name": "念心丨酷奇MV",
    "type": 3,
  "api": "./kuqimv_open.js"},


   {"key": "我的哔哩",
    "name": "念心丨我哔",
   "type": 3,
 "api": "./mybili_open.js"},

   {"key": "哔哩",
    "name": "念心丨哔哩",
   "type": 3,
   "api": "./bili_open.js",
   "ext":{"categories": "音乐#动画#电影#电视剧#番剧#综艺#国创#搞笑#单机游戏#沙雕动画#沙雕穿越#沙雕",
   "cookie": "DedeUserID=690781341;DedeUserID__ckMd5=cabc96906269c5b6;SESSDATA=2245ba24%2C1684212125%2C466fd%2Ab2;bili_jct=de6fdb60c10f8a83910aa55d79407b4e;"}},

   {"key": "哔哩直播",
    "name": "念心丨哔哩直播",
   "type": 3,
   "api": "./bililive_open.js",
   "ext":{"cookie": "DedeUserID=690781341;DedeUserID__ckMd5=cabc96906269c5b6;SESSDATA=2245ba24%2C1684212125%2C466fd%2Ab2;bili_jct=de6fdb60c10f8a83910aa55d79407b4e;"}},

   {"key": "虎牙直播",
    "name": "念心丨虎牙直播",
   "type": 3,
   "api": "./huya_open.js",
   "ext":{"from": "official",
    "custom": "2135, 一起看#6245, 放映厅#427, 流放之路#6399, 火炬之光：无限#2891, 魔力宝贝#2620, 跑跑卡丁车手游#162, 跑跑卡丁车#7691, 劲乐幻想#2675, 仙境传说RO"	}},

   
   {"key": "短视频",
    "name": "念心丨短片",
   "type": 3,
 "api": "./sharenice_open.js"},

   {"key": "酷我短剧",
    "name": "念心丨酷我短剧",
   "type": 3,
 "api": "./kuwo_open.js"},

   {"key": "种子短剧",
    "name": "采集丨种子短剧",
   "type": 3,
   "api": "./caiji.js",
   "ext": {"url": "http://zzdj.cc/api.php/provide/vod"}},

   
    {"key": "kuu",
      "name": "APP丨酷客",
    "type": 3,
    "api": "./appysv2.js",
  "ext": "https://www.kuin.one/api.php/app/"},

    {"key": "kuin",
      "name": "APP丨北极狐[V2]",
    "type": 3,
    "api": "./appysv2.js",
  "ext": "https://www.kuin.one/api.php/app/"},

    {"key": "jiageys",
      "name": "APP丨飞鸽影视[V2]",
    "type": 3,
    "api": "./appysv2.js",
  "ext": "http://www.jiageys.top/api.php/app/"},

    {"key": "yingszj",
      "name": "APP丨鑫鑫影视[V2]",
    "type": 3,
    "api": "./appysv2.js",
  "ext": "http://yingszj.xn--654a.cc/api.php/app/"},

    {"key": "weixiaolove",
      "name": "APP丨曲奇[V2]",
    "type": 3,
    "api": "./appysv2.js",
  "ext": "https://1234567.weixiaolove.cn/api.php/app/"},

    {"key": "ttmja",
      "name": "APP丨天天美剧[V2]",
    "type": 3,
    "api": "./appysv2.js",
  "ext": "https://www.ttmja.com/api.php/app/"},

    {"key": "996w",
      "name": "APP丨咕噜[V2]",
    "type": 3,
    "api": "./appysv2.js",
  "ext": "https://w.996w.top/api.php/app/"},

    {"key": "7k789",
      "name": "APP丨188影视[V1]",
    "type": 3,
    "api": "./appysv2.js",
  "ext": "https://www.7k789.com/mogai_api.php/v1.vod"},

    {"key": "ystv",
      "name": "APP丨追剧影视[V1]",
    "type": 3,
    "api": "./appysv2.js",
  "ext": "https://vip.ystv.lol/api.php/v1.vod"},

    
    {"key": "火狐资源",
      "name": "采集丨火狐",
    "type": 3,
    "api": "./caiji.js",
    "ext":{"url": "https://hhzyapi.com/api.php/provide/vod/from/hhm3u8",
      "categories": [ "内地剧",
      "欧美剧",
    "香港剧",
    "台湾剧",
    "马泰剧",
    "韩剧",
    "日剧",
    "动作片",
    "爱情片",
    "喜剧片",
    "科幻片",
    "恐怖片",
    "剧情片",
    "战争片",
    "灾难片",
    "悬疑片",
    "犯罪片",
    "奇幻片",
    "记录片",
    "",
    "动画片",
    "中国动漫",
    "日本动漫",
    "欧美动漫",
    "大陆综艺",
    "日韩综艺",
    "港台综艺",
  "欧美综艺"]	}},

    {"key": "红牛资源",
      "name": "采集丨红牛",
    "type": 3,
    "api": "./caiji.js",
    "ext":{"url": "https://www.hongniuzy2.com/api.php/provide/vod/from/hnm3u8/",
      "categories": ["国产剧",
      "港澳剧",
    "台湾剧",
    "欧美剧",
    "日剧",
    "泰剧",
    "韩剧",
    "综艺",
    "动漫",
    "动漫电影",
    "动作片",
    "喜剧片",
    "爱情片",
    "科幻片",
    "恐怖片",
    "剧情片",
    "战争片",
    "纪录片",
  ""]}},

    {"key": "速播资源",
      "name": "采集丨速播",
    "type": 3,
    "api": "./caiji.js",
    "ext":{"url": "https://subocaiji.com/api.php/provide/vod/from/subm3u8/",
      "categories": ["大陆剧",
      "台湾剧",
    "韩剧",
    "美剧",
    "港澳剧",
    "日剧",
    "泰剧",
    "动作片",
    "爱情片",
    "科幻片",
    "战争片",
    "剧情片",
    "恐怖片",
    "喜剧片",
    "纪录片",
    "",
    "动漫电影",
    "中国动漫",
    "日本动漫",
    "欧美动漫",
  "综艺"]}},

    {"key": "极速资源",
      "name": "采集丨极速",
    "type": 3,
    "api": "./caiji.js",
    "ext":{"url": "https://jszyapi.com/api.php/provide/vod/from/jsm3u8/",
      "categories": ["内地剧",
      "欧美剧",
    "香港剧",
    "台湾剧",
    "马泰剧",
    "韩剧",
    "日剧",
    "",
    "动作片",
    "爱情片",
    "喜剧片",
    "科幻片",
    "恐怖片",
    "剧情片",
    "战争片",
    "灾难片",
    "悬疑片",
    "犯罪片",
    "奇幻片",
    "记录片",
    "动画片",
    "中国动漫",
    "日本动漫",
    "欧美动漫",
    "大陆综艺",
    "日韩综艺",
    "港台综艺",
  "欧美综艺"]}},

    {"key": "光速资源",
      "name": "采集丨光速",
    "type": 3,
    "api": "./caiji.js",
    "ext":{"url": "https://api.guangsuapi.com/api.php/provide/vod/from/gsm3u8",
      "categories": ["大陆剧",
      "欧美剧",
    "港澳剧",
    "台湾剧",
    "泰剧",
    "韩剧",
    "日剧",
    "动作片",
    "爱情片",
    "喜剧片",
    "科幻片",
    "恐怖片",
    "战争片",
    "伦理片",
  "动漫电影"]}},

    {"key": "bfzyapi_t1",
      "name": "采集丨暴风",
    "type": 3,
    "api": "./caiji.js",
    "ext": {"url": "https://bfzyapi.com/api.php/provide/vod/",
      "categories":["国产剧",
      "韩国剧",
    "欧美剧",
    "日本剧",
    "香港剧",
    "台湾剧",
    "海外剧",
    "泰国剧",
    "纪录片",
    "动画片",
    "动漫片",
    "国产动漫",
    "日韩动漫",
    "欧美动漫",
    "港台动漫",
    "海外动漫",
    "动作片",
    "喜剧片",
    "恐怖片",
    "科幻片",
    "爱情片",
    "剧情片",
    "战争片",
    "大陆综艺",
    "港台综艺",
    "日韩综艺",
  "欧美综艺"]}},

    {"key": "1080zyk_t1",
      "name": "采集丨优质",
    "type": 3,
    "api": "./caiji.js",
    "ext": {"url": "https://api.1080zyku.com/inc/apijson.php",
      "categories":["搞笑",
      "音乐",
    "影视",
    "汽车",
    "国产剧",
    "韩国剧",
    "欧美剧",
    "日本剧",
    "台湾剧",
    "香港剧",
    "泰国剧",
    "海外剧",
    "记录片",
    "动画片",
    "国产动漫",
    "日韩动漫",
    "欧美动漫",
    "港台动漫",
    "动作片",
    "喜剧片",
    "爱情片",
    "科幻片",
    "恐怖片",
    "剧情片",
    "战争片",
    "大陆综艺",
    "港台综艺",
    "日韩综艺",
  "欧美综艺"]}},

    {"key": "kuaikan_t1",
      "name": "采集丨快看",
    "type": 3,
    "api": "./caiji.js",
    "ext": {"url": "https://kuaikan-api.com/api.php/provide/vod/from/kuaikan/",
      "categories":["国产剧",
      "韩国剧",
    "欧美剧",
    "日本剧",
    "泰剧",
    "港台剧",
    "新马剧",
    "其他剧",
    "纪录片",
    "动画电影",
    "日本动漫",
    "国产动漫",
    "欧美动漫",
    "港台动漫",
    "冒险片",
    "剧情片",
    "动作片",
    "喜剧片",
    "奇幻片",
    "恐怖片",
    "悬疑片",
    "惊悚片",
    "战争片",
    "歌舞片",
    "灾难片",
    "爱情片",
    "犯罪片",
    "科幻片",
    "经典片",
    "网络电影",
    "欧美综艺",
    "日本综艺",
    "韩国综艺",
    "国产综艺",
  "港台综艺"]}},

    {"key": "suoniapi_t1",
      "name": "采集丨索尼",
    "type": 3,
    "api": "./caiji.js",
    "ext": {"url": "https://suoniapi.com/api.php/provide/vod/from/snm3u8/",
      "categories":["爽文短剧",
      "足球",
    "篮球",
    "影视解说",
    "国产剧",
    "韩剧",
    "欧美剧",
    "日剧",
    "港剧",
    "台剧",
    "泰剧",
    "海外剧",
    "纪录片",
    "动画片",
    "国产动漫",
    "日韩动漫",
    "欧美动漫",
    "港台动漫",
    "海外动漫",
    "预告片",
    "动作片",
    "喜剧片",
    "爱情片",
    "科幻片",
    "恐怖片",
    "剧情片",
    "战争片",
    "大陆综艺",
    "日韩综艺",
    "港台综艺",
  "欧美综艺"]}},

    {"key": "qhm3u8_t1",
      "name": "采集丨奇虎",
    "type": 3,
    "api": "./caiji.js",
    "ext": {"url": "https://caiji.qhzyapi.com/api.php/provide/vod/from/qhm3u8/",
      "categories":["体育",
      "国产剧",
    "韩国剧",
    "欧美剧",
    "日本剧",
    "香港剧",
    "台湾剧",
    "泰国剧",
    "海外剧",
    "纪录片",
    "动画片",
    "国产动漫",
    "日本动漫",
    "欧美动漫",
    "欧美综艺",
    "日韩综艺",
    "大陆综艺",
    "港台综艺",
    "动作片",
    "喜剧片",
    "爱情片",
    "科幻片",
    "恐怖片",
    "战争片",
  "剧情片"]}},

          
    {"key": "阿里盘寻",
      "name": "(仅搜索)丨盘寻",
    "type": 3,
    "api": "./pansearch_open.js",
  "ext": "填入你的阿里token"},

    {"key": "阿里盘搜",
      "name": "(仅搜索)丨盘搜",
    "type": 3,
    "api": "./pansou_open.js",
  "ext": "填入你的阿里token"},

    {"key": "小纸条",
      "name": "(仅搜索)丨纸条",
    "type": 3,
    "api": "./xiaozhitiao_open.js",
  "ext": "填入你的阿里token"},

    {"key": "UP云搜",
      "name": "(仅搜索)丨云搜",
    "type": 3,
    "api": "./upyun_open.js",
  "ext": "填入你的阿里token"},

    {"key": "云盘4K",
      "name": "(仅搜索)丨云盘",
    "type": 3,
    "api": "./yunpan4k_open.js",
  "ext": "填入你的阿里token"}
  ]},

  "read": {
      "sites": [
      {
        "key": "13bqg",
        "name": "念心丨笔趣",
        "type": 10,
        "api": "./13bqg_open.js"
      },
   {"key": "老白故事",
    "name": "念心丨老白【🎧】",
   "type": 10,
 "api": "./lbgs_book_open.js"},

   {"key": "博看书苑",
    "name": "念心丨博看【🎧】",
   "type": 10,
 "api": "./bookan_book_open.js"}
    ]
  },

  "comic": {
      "sites": [
           {"key": "copymanga",
            "name": "念心丨拷贝漫画",
           "type": 20,
         "api": "./copymanga_open.js"},

            {"key": "baozimh",
              "name": "念心丨包子漫画",
            "type": 20,
          "api": "./baozimh_open.js"},

            {"key": "mkz",
              "name": "念心丨漫客漫画",
            "type": 20,
          "api": "./mkz_open.js"},

            {"key": "bengou",
              "name": "念心丨笨狗漫画",
            "type": 20,
          "api": "./bengou_open.js"}
      ]
  },

  "pan": {
    "sites": [
      {
        "key": "alist",

        "name": "Alist",

        "type": 40,

        "api": "./alist_open.js",

        "ext": [
          {
            "name": "Alist丨小雅",

            "server": "http://124.71.206.236:5678/",

            "startPage": "/",

            "showAll": false,

            "search": true,

            "headers": {
              "Authorization": ""
            },

            "params": {
              "/abc": {
                "password": "123"
              },

              "/abc/abc": {
                "password": "123"
              }
            }
          }
        ]
      }
    ]
  },

   "color": [
        {
            "light": { "bg": "https://i2.100024.xyz/2024/01/13/qrnuwt.webp",
             "bgMask": "0x50ffffff",
             "primary": "0xFF2B6C00",
             "onPrimary": "0xFFFFFFFF",
             "primaryContainer": "0xFFA6F779",
             "onPrimaryContainer": "0xFF082100",
             "secondary": "0xFF55624C",
             "onSecondary": "0xFFFFFFFF",
             "secondaryContainer": "0xFFD9E7CA",
             "onSecondaryContainer": "0xFF131F0D",
             "tertiary": "0xFF386666",
             "onTertiary": "0xFFFFFFFF",
             "tertiaryContainer": "0xFFBBEBEB",
             "onTertiaryContainer": "0xFF002020",
             "error": "0xFFBA1A1A",
             "onError": "0xFFFFFFFF",
             "errorContainer": "0xFFFFDAD6",
             "onErrorContainer": "0xFF410002",
             "background": "0xFFFDFDF5",
             "onBackground": "0xFF1A1C18",
             "surface": "0xFFFDFDF5",
             "onSurface": "0xFF1A1C18",
             "surfaceVariant": "0xFFE0E4D6",
             "onSurfaceVariant": "0xFF1A1C18",
             "inverseSurface": "0xFF2F312C",
             "onInverseSurface": "0xFFF1F1EA",
             "outline": "0xFF74796D",
             "outlineVariant": "0xFFC3C8BB",
             "shadow": "0xFF000000",
             "scrim": "0xFF000000",
             "inversePrimary": "0xFF8CDA60",
             "surfaceTint": "0xFF2B6C00" },

            "dark": { "bg": "https://i2.100024.xyz/2024/01/13/qrc37o.webp",
             "bgMask": "0x50000000",
             "primary": "0xFF8CDA60",
             "onPrimary": "0xFF133800",
             "primaryContainer": "0xFF1F5100",
             "onPrimaryContainer": "0xFFA6F779",
             "secondary": "0xFFBDCBAF",
             "onSecondary": "0xFF283420",
             "secondaryContainer": "0xFF3E4A35",
             "onSecondaryContainer": "0xFFD9E7CA",
             "tertiary": "0xFFA0CFCF",
             "onTertiary": "0xFF003737",
             "tertiaryContainer": "0xFF1E4E4E",
             "onTertiaryContainer": "0xFFBBEBEB",
             "error": "0xFFFFB4AB",
             "errorContainer": "0xFF93000A",
             "onError": "0xFF690005",
             "onErrorContainer": "0xFFFFDAD6",
             "background": "0xFF1A1C18",
             "onBackground": "0xFFE3E3DC",
             "outline": "0xFF8D9286",
             "onInverseSurface": "0xFF1A1C18",
             "inverseSurface": "0xFFE3E3DC",
             "inversePrimary": "0xFF2B6C00",
             "shadow": "0xFF000000",
             "surfaceTint": "0xFF8CDA60",
             "outlineVariant": "0xFF43483E",
             "scrim": "0xFF000000",
             "surface": "0xFF1A1C18",
             "onSurface": "0xFFC7C7C0",
             "surfaceVariant": "0xFF43483E",
             "onSurfaceVariant": "0xFFC7C7C0" }
        }
    ]
}
