名称：更新脚本

on:
    push:
        branches: [        分支：[主要]]

jobs:
    build:
        runs-on:         运行：ubuntu-latest

        strategy:
            matrix:
                node-version: [                节点版本：[18.x]]
                # 请参阅支持的 Node.js 发布时间表：https://nodejs.org/en/about/releases/# See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses:             - 使用：actions/checkout@v3
            - name :              - 名称：使用 Node.js $ { { Matrix.node-version } } { { matrix.node-version } }
              使用：               使用：actions/setup-node@v3
              和：
                  节点版本:                   节点版本：$ { {矩阵.节点版本} } {  {矩阵.节点版本}  }
                  缓存：“npm”
            -姓名：安装纱
              跑步：npm install yarn -g
            -跑步：纱线安装
            -跑步：纱线构建
            -运动：yarn m3u


            -名称：“杰基尔主题”
              跑步：mv ./_config.temp.yml ./m3u/_config.yml

            -姓名：部署
              用途：peaceiris/actions-gh-pages@v3
              和：
                  github_token ：$ {  { Secrets.GITHUB_TOKEN }  }
                  发布目录：./m3u
                  启用_jekyll：真
                  cname：43984927.github.io/iptv-sources-1

